[project]
name = "python-graphing-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "chardet>=7.6.0",
    "matplotlib>=3.11.2",
    "pandas>=3.0.6",
]

[project.scripts]
python-graphing-app = "python_graphing_app:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
